[profile.default]
optimizer = true
optimizer_runs = 10_000
src = "contracts"
out = "out"
libs = ["lib"]
remappings = [
  "@gnosis.pm/zodiac/contracts/=lib/zodiac/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "@gnosis.pm/safe-contracts/contracts/=lib/safe-contracts/contracts/",
]

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
berachain = "https://berachain-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sonic = "https://sonic-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
arbitrum = {key = "${ARBISCAN_API_KEY}", chain = 42161}
berachain = {key = "${BERASCAN_API_KEY}", chain = 80094, url = "https://api.berascan.com/api"}
sonic = {key = "${SONICSCAN_API_KEY}", chain = 146, url = "https://api.sonicscan.org/api"}
sepolia = {key = "${ETHERSCAN_API_KEY}", chain = 11155111}

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
